In [1]:
import numpy as np
import math as m

In [69]:
i = complex(0, 1)
beta =  np.array([[-1], [0], [1], [0]])
#beta = np.array([[0], [0], [1], [0]])
print(beta)

[[-1]
 [ 0]
 [ 1]
 [ 0]]


In [70]:
I = np.array([[1, 0], [0, 1]])
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0, -i], [i, 0]])
Z = np.array([[1, 0], [0, -1]])
mI = -I
mX = -X
mY = -Y
mZ = -Z
iI = i*I
iX = i*X
iY = i*Y
iZ = i*Z
miI = -i*I
miX = -i*X
miY = -i*Y
miZ = -i*Z

print(iY)

[[ 0.+0.j  1.-0.j]
 [-1.+0.j  0.+0.j]]


In [71]:
Pauli = [I, X, Y, Z, miI, miX, miY, miZ]
ls = [1, 2, 3]
2 in ls

True

In [72]:
lst = []
l = np.arange(0, len(Pauli), 1)
#print(l)

In [73]:
lst = []
for k in np.arange(0, len(Pauli), 1):
    for r in np.arange(0, len(Pauli), 1):
        P = np.kron(Pauli[k], Pauli[r])
        Pbeta = P.dot(beta)
        if  np.array_equal(Pbeta, beta) == True:
            lst.append([Pauli[k], Pauli[r]])
            print(P)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0  1  0]
 [ 0  0  0 -1]]
[[ 0.-0.j  0.-0.j -1.-0.j  0.-0.j]
 [ 0.-0.j  0.-0.j  0.-0.j -1.-0.j]
 [-1.-0.j  0.-0.j  0.-0.j  0.-0.j]
 [ 0.-0.j -1.-0.j  0.-0.j  0.-0.j]]
[[ 0.-0.j  0.-0.j -1.-0.j  0.-0.j]
 [ 0.-0.j  0.+0.j  0.-0.j  1.+0.j]
 [-1.-0.j  0.-0.j  0.-0.j  0.-0.j]
 [ 0.-0.j  1.+0.j  0.-0.j  0.+0.j]]


In [74]:
#print(lst)
print('number of stabilizers =', len(lst))

number of stabilizers = 4


Making a function from above code to calculate the stabilizer of any state vector

In [161]:
#import numpy as np
#import math as m

i = complex(0, 1)

I = np.array([[1, 0], [0, 1]])
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0, -i], [i, 0]])
Z = np.array([[1, 0], [0, -1]])
mI = -I
mX = -X
mY = -Y
mZ = -Z
iI = i*I
iX = i*X
iY = i*Y
iZ = i*Z
miI = -i*I
miX = -i*X
miY = -i*Y
miZ = -i*Z


#Pauli = [I, X, Y, Z, mI, mX, mY, mZ, iI, iX, iY, iZ, miI, miX, miY, miZ]
Pauli = [I, X, Y, Z, iI, iX, iY, iZ]

def Stab(beta):
    lst = []
    for k in np.arange(0, len(Pauli), 1):
        for r in np.arange(0, len(Pauli), 1):
            P = np.kron(Pauli[k], Pauli[r])
            Pbeta = P.dot(beta)
            if  np.array_equal(Pbeta, beta) == True:
                lst.append([Pauli[k], Pauli[r]])
                print(P)
    nos = len(lst)
    #print('number of stabilizers =', len(lst))
    return nos 
    

In [162]:
e = m.cos(m.pi/4) + i*m.sin(m.pi/4)
scalar = (1/m.sqrt(2))

psi = scalar * np.array([[1], [0], [0], [i/2]])

x = Stab(psi)
print('number of stabilizers is', x)

[[1 0]
 [0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[ 1  0]
 [ 0 -1]]
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]
number of stabilizers is 2
